//program to print names multiple time based on logic of for loop.(three differennt method)
public class ForLooping {
    
    public static void showName(){
        for(integer i = 1; i<=10; i++){
            system.debug('Nitish');
        }
    }
    
     public static void showName1(integer num){
        for(integer i = 1; i<=num; i++){
            system.debug('sat');
        }
    }
    
     public static void showName2(){
        for(integer i = 10; i<=10; i--){
            system.debug('Jeett');
        }
    }

}
